create database manufacture;
use manufacture;
select * from man_csv;
rename table man_csv to Manufacture;
-- Total Rejected Quantity(KPI)
SELECT   CONCAT(FORMAT(SUM(REJECTED_QTY)/1000,2), " K") TOTAL_REJECTED_QUANTITY FROM MANUFACTURE;

-- TOTAL MANUFACTURED QUANTITY(KPI)
SELECT * FROM MANUFACTURE;
SELECT concat(format(SUM(TODAY_MANUFACTURED_QTY)/1000000,2)," M")  Total_Manufactured_Quantity FROM MANUFACTURE;

-- TOTAL BUYERS(KPI)

SELECT  CONCAT(FORMAT(COUNT(BUYER)/1000,2), " K") AS TOTAL_BUYERS FROM MANUFACTURE;

-- TOTAL PRESS QUANTITY(KPI)

SELECT CONCAT(FORMAT(SUM(PRESS_QTY)/1000000,2), " M") TOTAL_PRESS_QUANTITY FROM MANUFACTURE;

-- TOTAL PROCESSED QUANTITY (KPI)

SELECT CONCAT(FORMAT(SUM(PROCESSED_QTY)/1000000,2), " M") AS TOTAL_PROCESSED_QUANTITY  FROM MANUFACTURE;

-- TOTAL PRODUCED QUANTITY (KPI)
SELECT CONCAT(FORMAT(SUM(PRODUCED_QTY)/1000000,2), " M")  TOTAL_PRODUCED_QUANTITY FROM MANUFACTURE;


-- TOTAL VALUES

SELECT  CONCAT(FORMAT(ROUND(SUM(TOTAL_VALUE),0)/10000000,2), " CRORES") FROM manufacture;

-- EMPLOYEE WISE TOP 3 REJECTED QUANTITY

SELECT EMP_NAME , CONCAT(FORMAT(SUM(REJECTED_QTY)/10000,2), " L") TOTAL_REJECTED_QUANTITY FROM MANUFACTURE
GROUP BY 1
ORDER BY 2 DESC
LIMIT 3;

-- BUYER WISE PRODUCED QUANTITY 
SELECT BUYER, SUM(PRODUCED_QTY) AS TOTAL_QUANTITY FROM manufacture
group by 1
ORDER BY 2;
 
-- STORED PROCEDGURE (EMPLOYEE WISE)

call manufacture.new_procedure('SHRUTI SINGH');

-- TOP TEN MACHINE WISE REJECTED QUANTITY (WINDOW FUNCTION)
SELECT MACHINE_CODE, SUM(REJECTED_QTY) REJECTED_QUANTITY , DENSE_RANK() OVER( ORDER BY SUM(REJECTED_QTY) desc) AS RANK_
FROM MANUFACTURE 
GROUP BY 1
LIMIT 10;
-- INDEX FOR THE FASTER PERFORMACE OF THE MANUFACTURING DATASET
 CREATE INDEX TEST ON MANUFACTURE(REJECTED_QTY); 
 
 -- SUB QUERY (CUSTOMER  WISE REJECTED QUANTITY TOP 5)
 SELECT CUST_NAME, SUM(REJECTED_QTY) AS TOTAL_REJECTED_QTY FROM MANUFACTURE
 GROUP BY 1
 ORDER BY 2 DESC
 LIMIT 5;
